// Auto generated by utensor-cli

#ifndef ___TMP_BUILD_UTENSOR-MODEL_TRAINED_H
#define ___TMP_BUILD_UTENSOR-MODEL_TRAINED_H
#include "uTensor/core/context.hpp"
void get_trained_ctx(Context& ctx, Tensor* input_0);
#endif // ___TMP_BUILD_UTENSOR-MODEL_TRAINED_H